apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jalapeno
  name: telemetry-processor
  labels:
    app: telemetry-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry-processor
  template:
    metadata:
      labels:
        app: telemetry-processor
    spec:
      containers:
      - name: telemetry-processor
        image: iejalapeno/telemetry-processor:latest
        imagePullPolicy: Always
      - args:
          - --v
          - "5"
          - --message-server
          - "broker.jalapeno:9092"
          - --database-server
          - "http://arangodb.jalapeno:8529"
          - --database-name
          - "jalapeno"
        volumeMounts:
            - name: credentials
              mountPath: /credentials
      volumes:
        - name: credentials
          secret:
            secretName: jalapeno
        env:
          - name: PYTHONUNBUFFERED
            value: "1"
      imagePullSecrets:
        - name: regcred
